# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba85768e5bbf9c5b5390518fcfa25eed3fc9241d55f3dcc56ee4b7aabf1b64acb6c33a2248dba829a3fbc5b43f5910a537cdb4ac64ee83d89fe9581e95708b4d

test:
  secret_key_base: e400fd77df6a09b515a465c7b1b133734aa72d74870d466d825211f4e4890f854c763eed15adaed12a458ceef176d68d0c76343f58af2f1852bce3366c0a2e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
